{
 "title": "SmartHome Readings",
 "time": { "from": "2026-01-23T12:36:54.176Z", "to": "2026-01-23T15:12:48.161Z" },
 "panels": [
  { "title": "Home Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature reading",
   "type": "timeseries",
   "description": "Temperature of the house",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  "
    }
   ]
  },
  {
   "title": "Pole status now",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pole\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Fan Status Now",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Clothes Pole Status history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pole\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> drop(columns: [\"id\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Fan status history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 3 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"fan\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> drop(columns: [\"id\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Door Status Now",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"door\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Window Status Now",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"window\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Door status history",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"door\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"id\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Window status History",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"window\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"id\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Humidity Record",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")"
    }
   ]
  },
  {
   "title": "Pressure Record",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pressure\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")"
    }
   ]
  },
  {
   "title": "Weather Record",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> drop(columns: [\"id\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "BinaryWeather [not for viewing]",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"weather\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> map(fn: (r) => ({ \r\n      r with _value: if r._value == \"Raining\" then 1.0 else 0.0 \r\n    }))"
    }
   ]
  },
  {
   "title": "Binary Door (not for viewing)",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 1, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"door\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> map(fn: (r) => ({ \r\n      r with _value: if r._value == \"Open\" then 1.0 else 0.0 \r\n    }))"
    }
   ]
  },
  {
   "title": "Binary Window",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 2, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"window\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> map(fn: (r) => ({ \r\n      r with _value: if r._value == \"Open\" then 1.0 else 0.0 \r\n    }))"
    }
   ]
  },
  {
   "title": "Binary Pole",
   "type": "timeseries",
   "gridPos": { "h": 1, "w": 1, "x": 3, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"readings\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pole\")\r\n  |> filter(fn: (r) => r[\"id\"] == \"pi4smarthome\")\r\n  |> map(fn: (r) => ({ \r\n      r with _value: if r._value == \"Extend\" then 1.0 else 0.0 \r\n    }))"
    }
   ]
  }
 ]
}